LocalSearchBatching:
  NN_FiFo:
    routing_class: NearestNeighbourhoodRouting
    start_batching_class: OrderNrFifoBatching

  SShape_FiFo:
    routing_class: SShapeRouting
    start_batching_class: OrderNrFifoBatching

  SShape_Random:
    routing_class: SShapeRouting
    start_batching_class: RandomBatching
    start_batching_kwargs:
      seed: pipeline.seed

  RR_FiFo:
    routing_class: RatliffRosenthalRouting
    start_batching_class: OrderNrFifoBatching